### ISSUE TITLE
Code correction.

### ISSUE THREAD

**Issue by michelmelosilva** [IITD-COMPUTER-VISION-GROUP/Egomotion_with_Local_Loop_Closures#1]
Dear authors.
Thank you for the code.

I found some issues which I would like to share.

In the file CMakeLists.txt the order of the link libraries is wrong:
```
-target_link_libraries(ELLC ${OpenCV_LIBS} boost_system boost_thread ELLC-helpers)
+target_link_libraries(ELLC ELLC-helpers ${OpenCV_LIBS} boost_system boost_thread)
```
After running the program, I used the VisualizeTrajectory script to check the results, and the output was confusing. Then I realize the order during the file read was wrong. 

in file matlab_scripts/VisualizeTrajectory.m
```matlab
-w1=B(i,2);  
+w1=B(i,3);  
-w2=B(i,3); 
+w2=B(i,4);
-w3=B(i,4);
+w3=B(i,5);

p=[3 3 3]';% Dummy point

-v1=B(i,5);  
+v1=B(i,6);  
-v2=B(i,6);  
+v2=B(i,7);  
-v3=B(i,7);  
+v3=B(i,8);
```

**Comment by patrasuvam** [comment]
Thanks
